# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S7qkdcKlAJE_mP2kksejh1_8VlVnYz1i
"""

f = open("num.txt", "r")
for numero in f:
  valor= range(2,int(numero))
  contador = 0
  for n in valor:
   if int(numero) % n == 0:
      contador +=1
 
  if contador > 0 :
   print(numero,"   El número no es primo" )
  else:
    print(numero,"  El nÚmero es primo")