# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b4yNB20pfHw2oy-VLvCxhubzwauxSxTA
"""

with open ("test.txt","w") as fwriter:
  fwriter.write("Hola mundo")

with open ("test.txt","r") as freader:
  lineas = freader.readlines()
  for x in range(len(lineas)):
    print(x,"  -  ", lineas [x])