# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BP6d6emODGigrOSUaA-knS0iXsDOnr9o
"""



num = input("digite la canitidad de numeros a validar")
for i in num:
  acu = input("digite el numero a validar")
  con = (int(acu))%(int(num))
  if con == 0:
    print(acu," Es primo")
  if con !=0:
    print(acu ,"No es primo")

